######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 20 09:21:33 2014
######################################################################

TEMPLATE = app
TARGET = AOSC-LiveKit
LIBS += -lparted
DEPENDPATH += . data include src Gui include Window
QT += widgets core gui
INCLUDEPATH += . include


# Input
HEADERS += include/dialogbox.h \
           include/installermain.h \
           include/installerpage.h \
           include/partitionselect.h \
           include/workingthread.h
SOURCES += src/dialogbox.cpp \
           src/installermain.cpp \
           src/installerpage.cpp \
           src/main.cpp \
           src/partitionselect.cpp \
           src/workingthread.cpp
RESOURCES += data/resources.qrc
