######################################################################
# Automatically generated by qmake (3.0) Thu Jul 31 23:21:17 2014
######################################################################

TEMPLATE = app
TARGET = installer-qt
QT += widgets core gui
DEPENDPATH += . Gui include Window
INCLUDEPATH += . include

# Input
HEADERS += include/installermain.h include/installerpage.h
SOURCES += src/installermain.cpp src/installerpage.cpp src/main.cpp

RESOURCES += \
    data/resources.qrc
