######################################################################
# Automatically generated by qmake (3.0) Thu Aug 14 13:12:58 2014
######################################################################

TEMPLATE = app
QT += widgets core gui
TARGET = installer-qt
INCLUDEPATH += . include
LIBS += -lparted
QMAKE_CXXFLAGS  += -g -ggdb

# Input
HEADERS += include/installermain.h include/installerpage.h \
    include/partitionselect.h
SOURCES += src/installermain.cpp src/installerpage.cpp src/main.cpp \
    src/partitionselect.cpp
RESOURCES += data/resources.qrc
