######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 28 10:20:10 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include src
INCLUDEPATH += . include

# Input
HEADERS += include/AOSC-Installer-Basic-UI.h \
           include/AOSC-Installer-Core.h \
           include/AOSC-Installer-Non-UI.h
SOURCES += src/GUI.cpp src/main.cpp src/Non-GUI.cpp
