#!/bin/bash
USERNAME=/tmp/username
PASSWD=/tmp/passwd

whiptail --title "User Configuration" --inputbox "Please tell me your username (lower-case letter and numbers only please,\nand no space are allowed." 15 70 2>$USERNAME
whiptail --title "User Configuration" --inputbox "And your password please" 15 65 2>$PASSWD
whiptail --title "User Configuration" --inputbox "Please repeat the password" 15 65 2>$PASSWD
whiptail --title "User Configuration" --infobox "Now configuring the user and its password..." 10 65
usermod -l `cat $USERNAME` -md /home/`cat $USERNAME` misaka
/usr/sbin/cpw.sh 
