#!/bin/bash
BOOT=/tmp/boot_dev
ESP=/tmp/esp
mount --bind /dev /target/dev
mount --bind /proc /target/proc
mount --bind /sys /target/sys
mount -vt devpts devpts /target/dev/pts -o gid=5,mode=620

whiptail --title "Post-Copy Configuration" --inputbox "Plese tell me the device name of the boot disk" 12 65 2> $BOOT
whiptail --title "Post-Copy Configuration" --msgbox "We are now going to install GRUB on your system" 12 65 
whiptail --title "EFI Users!!!" --yesno "Are you running on EFI?" 12 65 
if [ $exitstatus = 0 ]; then
	whiptail --title "EFI Uers!!!" --inputbox "Please tell me the partition where your ESP (EFI System\nPartition) is located." 12 70 2> $ESP
	mkdir -v /target/efi
	mount `cat $ESP` /target/efi
	chroot /target grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=CentralPoint --recheck
	chroot /target grub-mkconfig -o /boot/grub/grub.cfg
else
	whiptail --title "Post-Copy Configuration" --infobox "Installing GRUB to `cat $BOOT`" 12 65
	chroot /target grub-install --target=i386-pc `cat $BOOT` --recheck
	chroot /target grub-mkconfig -o /boot/grub/grub.cfg
fi
whiptail --title "Post-Copy Configuration" --infobox "Configuring /etc/fstab file..." 12 65
echo "$TARGET / $FS defaults 1 1" > /target/etc/fstab
chroot /target install-user
install-complete
