#!/bin/bash
DIRS=(/mnt/squash/*)
DEST="/target"
 
dialog --title "Copying System Files..." --gauge "Copying directory" 10 75 < <(
   n=${#DIRS[*]}; 
 
   i=0
 
   for f in "${DIRS[@]}"
   do
      PCT=$(( 100*(++i)/n ))
 
cat <<EOF
XXX
$PCT
Copying directory "$f" ...
XXX
EOF

   cp -arv $f $DEST &>/dev/null
   done
)
install-configure
rm $DEST/install-started
