#!/bin/bash
whiptail --title "CentralPoint/Non-GUI Distribution Installer" --yesno "This installer is designed for CentralPoint or other Community Distribution \nusing bash or virtual terminal as default interface. \n\n\nDo you want to continue? Confirms Misaka." 15 80
exitstatus=$?
if [ $exitstatus = 0 ]
then
	install-staging
else
	whiptail --title "Wonders Misaka" --yesno "Are you sure that you want to quit? Confirms Misaka." 8 40
	exitstatus=$?
	if [ $exitstatus = 0 ]
	then
		exit 0
		echo "(Exit status was $exitstatus)"
	else
		install-prepare
		echo "(Exit status was $exitstatus)"
	fi
fi 
echo "(Exit status was $exitstatus)"

