#!/bin/bash
whiptail --title "CentralPoint/Non-GUI Distribution Installer" --msgbox "Here's what Misaka is going to do with you:\n\n* License Agreement\n* Partition Your Hard Drive\n* Install System\n* Configure and Personalize\n* Voila!" 20 80
whiptail --title "License Agreement" --yesno "CentralPoint and other distribution from AOSC license under LGPL,\nfor further reading go to:\n\nhttp://www.gnu.org/copyleft/lesser.html\n\nSystem Info:\n\n`lsb_release -a`\n\nDo you agree and still want to continue? Asks Misaka." 20 80
exitstatus=$?
if [ $exitstatus = 0 ]; then
	install-partition
else
	whiptail --title "Sorry" --msgbox "We cannot continue the installation unless you agree with the the License Agreement, explains Misaka." 8 50
	exit 0
fi
