#!/bin/bash
export TARGET=/tmp/target_disk
export FS=/tmp/target_fs

whiptail --title "Partition Your Hard Drive [Use with care, warns Misaka]" --msgbox "Here's your partition table so far:\n\n`fdisk -l`" 24 80
whiptail --title "Partition Your Hard Drive [Use with care, warns Misaka]" --yesno "Now we will pop you into GNU Parted to do some partitioning...\n\nDo you need to change anything? Asks Misaka" 15 65
exitstatus=$?
if [ $exitstatus = 0 ]; then
	parted
else
	true
fi
whiptail --title "Partition Your Hard Drive [Use with care, warns Misaka]" --inputbox "Please tell me the device name of your target partition: " 10 40 \
2> "$TARGET"
whiptail --title "Partition Your Hard Drive [Use with care, warns Misaka]" --menu "Please choose a preferred filesystem from below" 15 80 6 \
"ext3" "Third Extended File System" \
"ext4" "Fourth Extended File System" \
"jfs" "Journaled File System" \
"btrfs" "B-tree File System" \
"xfs" "XFS" 2> $FS
whiptail --title "ATTENTION" --yesno "Formatting a partition will cause data lost,\nand _USUALLY_ hard to recover!\n\nAre you sure that you want to format `cat $TARGET` with `cat $FS`? Misaka is trying to confirm your decision." 15 65 
exitstatus=$?
if [ $exitstatus = 0 ]; then
        mkfs.`cat $FS` `cat $TARGET`
	bash install-install
else
        whiptail --title "Error..." --msgbox "In early stage development, we don't support\ninstalling without formating the target partition.\n\nWe apologize for the inconvenience. Apologizes Misaka."  12 65
	exit 1
fi
