#!/bin/bash
cat /target/etc/bashrc | head -n -1 > /target/etc/bashrc
whiptail --title "System Installation Complete!" --infobox "Installation has successfully completed,\n your computer will be now restarted" 15 75
sleep 5
sync
reboot